#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u DPAN/src/main.py --template DPAN --data_test Set5 --scale 2 --test_only --pre_train DPAN/experiment/trained_model/DPAN_BI_X2.pt --save_results"$@" 


